# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\linmou202\Programing\Compile_Files\Database_Basics\EP_2\src\frontend\ui\adm_mtnc.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets, QtSql
from utils.utils import *
from ui.Ui_error import Ui_error_box


class Ui_adm_mtnc_interface(object):
    def setupUi(self, adm_mtnc_interface):
        adm_mtnc_interface.setObjectName("adm_mtnc_interface")
        adm_mtnc_interface.resize(1354, 795)
        font = QtGui.QFont()
        font.setPointSize(12)
        adm_mtnc_interface.setFont(font)
        self.table = QtWidgets.QTableWidget(adm_mtnc_interface)
        self.table.setGeometry(QtCore.QRect(60, 310, 1241, 431))
        self.table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.table.setRowCount(0)
        self.table.setColumnCount(5)
        self.table.setObjectName("table")
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(4, item)
        self.table.verticalHeader().setVisible(False)
        self.label = QtWidgets.QLabel(adm_mtnc_interface)
        self.label.setGeometry(QtCore.QRect(70, 40, 61, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(adm_mtnc_interface)
        self.label_2.setGeometry(QtCore.QRect(70, 80, 61, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(adm_mtnc_interface)
        self.label_3.setGeometry(QtCore.QRect(70, 120, 61, 31))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(adm_mtnc_interface)
        self.label_4.setGeometry(QtCore.QRect(70, 200, 61, 31))
        self.label_4.setObjectName("label_4")
        self.complete = QtWidgets.QPushButton(adm_mtnc_interface)
        self.complete.setGeometry(QtCore.QRect(1160, 130, 131, 61))
        self.complete.setObjectName("complete")
        self.label_5 = QtWidgets.QLabel(adm_mtnc_interface)
        self.label_5.setGeometry(QtCore.QRect(70, 160, 71, 31))
        self.label_5.setObjectName("label_5")
        self.mtid = QtWidgets.QLineEdit(adm_mtnc_interface)
        self.mtid.setGeometry(QtCore.QRect(150, 40, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.mtid.setFont(font)
        self.mtid.setText("")
        self.mtid.setObjectName("mtid")
        self.flatid = QtWidgets.QLineEdit(adm_mtnc_interface)
        self.flatid.setGeometry(QtCore.QRect(150, 80, 211, 31))
        self.flatid.setObjectName("flatid")
        self.roomid = QtWidgets.QLineEdit(adm_mtnc_interface)
        self.roomid.setGeometry(QtCore.QRect(150, 120, 211, 31))
        self.roomid.setObjectName("roomid")
        self.year = QtWidgets.QLineEdit(adm_mtnc_interface)
        self.year.setGeometry(QtCore.QRect(150, 160, 51, 31))
        self.year.setObjectName("year")
        self.label_6 = QtWidgets.QLabel(adm_mtnc_interface)
        self.label_6.setGeometry(QtCore.QRect(210, 160, 21, 31))
        self.label_6.setObjectName("label_6")
        self.month = QtWidgets.QLineEdit(adm_mtnc_interface)
        self.month.setGeometry(QtCore.QRect(230, 160, 41, 31))
        self.month.setText("")
        self.month.setObjectName("month")
        self.label_7 = QtWidgets.QLabel(adm_mtnc_interface)
        self.label_7.setGeometry(QtCore.QRect(280, 160, 21, 31))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(adm_mtnc_interface)
        self.label_8.setGeometry(QtCore.QRect(350, 160, 21, 31))
        self.label_8.setObjectName("label_8")
        self.day = QtWidgets.QLineEdit(adm_mtnc_interface)
        self.day.setGeometry(QtCore.QRect(300, 160, 41, 31))
        self.day.setText("")
        self.day.setObjectName("day")
        self.label_9 = QtWidgets.QLabel(adm_mtnc_interface)
        self.label_9.setGeometry(QtCore.QRect(70, 220, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.query = QtWidgets.QPushButton(adm_mtnc_interface)
        self.query.setGeometry(QtCore.QRect(1160, 30, 131, 61))
        self.query.setObjectName("query")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(adm_mtnc_interface)
        self.plainTextEdit.setGeometry(QtCore.QRect(150, 200, 801, 91))
        self.plainTextEdit.setPlainText("")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.quit = QtWidgets.QPushButton(adm_mtnc_interface)
        self.quit.setGeometry(QtCore.QRect(1160, 230, 131, 61))
        self.quit.setObjectName("quit")

        self.retranslateUi(adm_mtnc_interface)
        self.query.clicked.connect(lambda x : find_record(adm_mtnc_interface))
        self.complete.clicked.connect(lambda x : complete_record(adm_mtnc_interface))
        self.quit.clicked.connect(lambda x : discard_record(adm_mtnc_interface))

    def retranslateUi(self, adm_mtnc_interface):
        _translate = QtCore.QCoreApplication.translate
        adm_mtnc_interface.setWindowTitle(_translate("adm_mtnc_interface", "我的维修任务"))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("adm_mtnc_interface", "维修号"))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("adm_mtnc_interface", "地点"))
        item = self.table.horizontalHeaderItem(2)
        item.setText(_translate("adm_mtnc_interface", "内容"))
        item = self.table.horizontalHeaderItem(3)
        item.setText(_translate("adm_mtnc_interface", "提交时间"))
        item = self.table.horizontalHeaderItem(4)
        item.setText(_translate("adm_mtnc_interface", "提交者"))
        self.label.setText(_translate("adm_mtnc_interface", "维修号："))
        self.label_2.setText(_translate("adm_mtnc_interface", "公寓号："))
        self.label_3.setText(_translate("adm_mtnc_interface", "房间号："))
        self.label_4.setText(_translate("adm_mtnc_interface", "内容："))
        self.complete.setText(_translate("adm_mtnc_interface", "完成"))
        self.label_5.setText(_translate("adm_mtnc_interface", "提交时间："))
        self.label_6.setText(_translate("adm_mtnc_interface", "年"))
        self.label_7.setText(_translate("adm_mtnc_interface", "月"))
        self.label_8.setText(_translate("adm_mtnc_interface", "日"))
        self.label_9.setText(_translate("adm_mtnc_interface", "(100字以内)"))
        self.query.setText(_translate("adm_mtnc_interface", "查询"))
        self.quit.setText(_translate("adm_mtnc_interface", "放弃"))

def find_record(adm_mtnc_interface):
    query = QtSql.QSqlQuery()
    query_string = "select `mtid`, `request`, `flatid`, `roomid`, `stuid`, `subtime` from `maintenance` where `status` = 1 and `admid` = :username"

    if(adm_mtnc_interface.ui.mtid.text() != '' and adm_mtnc_interface.ui.mtid.text().isdigit()):
        query_string = query_string + " and `maintenance`.`mtid` = :mtid"
    if(adm_mtnc_interface.ui.flatid.text() != ''):
        query_string = query_string + " and `maintenance`.`flatid` = :flatid"
    if(adm_mtnc_interface.ui.roomid.text() != ''):
        query_string = query_string + " and `maintenance`.`roomid` = :roomid"
    if(adm_mtnc_interface.ui.year.text() != ''):
        query_string = query_string + " and year(`maintenance`.`subtime`) = :year"
    if(adm_mtnc_interface.ui.month.text() != ''):
        query_string = query_string + " and month(`maintenance`.`subtime`) = :month"
    if(adm_mtnc_interface.ui.day.text() != ''):
        query_string = query_string + " and day(`maintenance`.`subtime`) = :day"
    if(adm_mtnc_interface.ui.plainTextEdit.toPlainText() != ''):
        query_string = query_string + " and `maintenance`.`request` like :request"

    query.prepare(query_string)
    query.bindValue(':username', adm_mtnc_interface.admid)
    if(adm_mtnc_interface.ui.mtid.text() != '' and adm_mtnc_interface.ui.mtid.text().isdigit()):
        query.bindValue(':mtid', int(adm_mtnc_interface.ui.mtid.text()))
    query.bindValue(':flatid', adm_mtnc_interface.ui.flatid.text())
    query.bindValue(':roomid', adm_mtnc_interface.ui.roomid.text())
    query.bindValue(':year', adm_mtnc_interface.ui.year.text())
    query.bindValue(':month', adm_mtnc_interface.ui.month.text())
    query.bindValue(':day', adm_mtnc_interface.ui.day.text())
    query.bindValue(':request', '%' + adm_mtnc_interface.ui.plainTextEdit.toPlainText() + '%')
    query.exec()

    adm_mtnc_interface.ui.table.setRowCount(0)

    while query.next():
        adm_mtnc_interface.ui.table.insertRow(adm_mtnc_interface.ui.table.rowCount())
        i = adm_mtnc_interface.ui.table.rowCount() - 1
        adm_mtnc_interface.ui.table.setItem(i, 0, QtWidgets.QTableWidgetItem(str(query.value(0))))
        adm_mtnc_interface.ui.table.setItem(i, 1, QtWidgets.QTableWidgetItem(concat_address(query.value(2), query.value(3))))
        adm_mtnc_interface.ui.table.setItem(i, 2, QtWidgets.QTableWidgetItem(query.value(1)))
        adm_mtnc_interface.ui.table.setItem(i, 3, QtWidgets.QTableWidgetItem(decode_date(query.value(5))))
        adm_mtnc_interface.ui.table.setItem(i, 4, QtWidgets.QTableWidgetItem(query.value(4)))

def complete_record(adm_mtnc_interface):
    if(adm_mtnc_interface.ui.mtid.text() == ''  or not adm_mtnc_interface.ui.mtid.text().isdigit()):
        error_msgbox = QtWidgets.QDialog()
        error_msgbox.setAttribute(QtCore.Qt.WA_DeleteOnClose, True)
        error_msgbox.ui = Ui_error_box()
        error_msgbox.ui.setupUi(error_msgbox, "必须提供维修号")
        error_msgbox.exec_()
    else:
        query = QtSql.QSqlQuery()
        query.prepare("call complete_maintenance_record(:mtid, :username, @stat)")
        query.bindValue(':username', adm_mtnc_interface.admid)
        query.bindValue(':mtid', int(adm_mtnc_interface.ui.mtid.text()))
        query.exec()
        query.exec("select @stat")
        query.next()

        if (query.value(0) > 0):
            error_msgbox = QtWidgets.QDialog()
            error_msgbox.setAttribute(QtCore.Qt.WA_DeleteOnClose, True)
            error_msgbox.ui = Ui_error_box()
            error_msgbox.ui.setupUi(error_msgbox, "无法完成该请求")
            error_msgbox.exec_()
        else:
            find_record(adm_mtnc_interface)

def discard_record(adm_mtnc_interface):
    if(adm_mtnc_interface.ui.mtid.text() == ''  or not adm_mtnc_interface.ui.mtid.text().isdigit()):
        error_msgbox = QtWidgets.QDialog()
        error_msgbox.setAttribute(QtCore.Qt.WA_DeleteOnClose, True)
        error_msgbox.ui = Ui_error_box()
        error_msgbox.ui.setupUi(error_msgbox, "必须提供维修号")
        error_msgbox.exec_()
    else:
        query = QtSql.QSqlQuery()
        query.prepare("call discard_maintenance_record(:mtid, :username, @stat)")
        query.bindValue(':username', adm_mtnc_interface.admid)
        query.bindValue(':mtid', int(adm_mtnc_interface.ui.mtid.text()))
        query.exec()
        query.exec("select @stat")
        query.next()

        if (query.value(0) > 0):
            error_msgbox = QtWidgets.QDialog()
            error_msgbox.setAttribute(QtCore.Qt.WA_DeleteOnClose, True)
            error_msgbox.ui = Ui_error_box()
            error_msgbox.ui.setupUi(error_msgbox, "无法放弃该请求")
            error_msgbox.exec_()
        else:
            find_record(adm_mtnc_interface)