# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\linmou202\Programing\Compile_Files\Database_Basics\EP_2\src\frontend\ui\adm_visit.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets, QtSql
from utils.utils import *


class Ui_adm_visit_interface(object):
    def setupUi(self, adm_visit_interface):
        adm_visit_interface.setObjectName("adm_visit_interface")
        adm_visit_interface.resize(1354, 825)
        font = QtGui.QFont()
        font.setPointSize(12)
        adm_visit_interface.setFont(font)
        self.label = QtWidgets.QLabel(adm_visit_interface)
        self.label.setGeometry(QtCore.QRect(70, 80, 81, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(adm_visit_interface)
        self.label_2.setGeometry(QtCore.QRect(70, 120, 81, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(adm_visit_interface)
        self.label_3.setGeometry(QtCore.QRect(70, 160, 81, 31))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(adm_visit_interface)
        self.label_4.setGeometry(QtCore.QRect(70, 240, 71, 31))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(adm_visit_interface)
        self.label_5.setGeometry(QtCore.QRect(70, 200, 81, 31))
        self.label_5.setObjectName("label_5")
        self.visid = QtWidgets.QLineEdit(adm_visit_interface)
        self.visid.setGeometry(QtCore.QRect(150, 80, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.visid.setFont(font)
        self.visid.setText("")
        self.visid.setObjectName("visid")
        self.name = QtWidgets.QLineEdit(adm_visit_interface)
        self.name.setGeometry(QtCore.QRect(150, 120, 211, 31))
        self.name.setObjectName("name")
        self.telephone = QtWidgets.QLineEdit(adm_visit_interface)
        self.telephone.setGeometry(QtCore.QRect(150, 160, 211, 31))
        self.telephone.setObjectName("telephone")
        self.year = QtWidgets.QLineEdit(adm_visit_interface)
        self.year.setGeometry(QtCore.QRect(150, 200, 51, 31))
        self.year.setText("")
        self.year.setObjectName("year")
        self.label_6 = QtWidgets.QLabel(adm_visit_interface)
        self.label_6.setGeometry(QtCore.QRect(210, 200, 21, 31))
        self.label_6.setObjectName("label_6")
        self.month = QtWidgets.QLineEdit(adm_visit_interface)
        self.month.setGeometry(QtCore.QRect(230, 200, 41, 31))
        self.month.setText("")
        self.month.setObjectName("month")
        self.label_7 = QtWidgets.QLabel(adm_visit_interface)
        self.label_7.setGeometry(QtCore.QRect(280, 200, 21, 31))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(adm_visit_interface)
        self.label_8.setGeometry(QtCore.QRect(350, 200, 21, 31))
        self.label_8.setObjectName("label_8")
        self.day = QtWidgets.QLineEdit(adm_visit_interface)
        self.day.setGeometry(QtCore.QRect(300, 200, 41, 31))
        self.day.setText("")
        self.day.setObjectName("day")
        self.query_reservation = QtWidgets.QPushButton(adm_visit_interface)
        self.query_reservation.setGeometry(QtCore.QRect(1040, 40, 251, 291))
        self.query_reservation.setObjectName("query_reservation")
        self.reason = QtWidgets.QPlainTextEdit(adm_visit_interface)
        self.reason.setGeometry(QtCore.QRect(150, 240, 801, 91))
        self.reason.setPlainText("")
        self.reason.setObjectName("reason")
        self.res_table = QtWidgets.QTableWidget(adm_visit_interface)
        self.res_table.setGeometry(QtCore.QRect(70, 350, 1221, 431))
        self.res_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.res_table.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.res_table.setRowCount(0)
        self.res_table.setColumnCount(7)
        self.res_table.setObjectName("res_table")
        item = QtWidgets.QTableWidgetItem()
        self.res_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.res_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.res_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.res_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.res_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.res_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.res_table.setHorizontalHeaderItem(6, item)
        self.res_table.verticalHeader().setVisible(False)
        self.label_10 = QtWidgets.QLabel(adm_visit_interface)
        self.label_10.setGeometry(QtCore.QRect(70, 40, 81, 31))
        self.label_10.setObjectName("label_10")
        self.resid = QtWidgets.QLineEdit(adm_visit_interface)
        self.resid.setGeometry(QtCore.QRect(150, 40, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.resid.setFont(font)
        self.resid.setText("")
        self.resid.setObjectName("resid")
        self.label_9 = QtWidgets.QLabel(adm_visit_interface)
        self.label_9.setGeometry(QtCore.QRect(390, 80, 81, 31))
        self.label_9.setObjectName("label_9")
        self.stuid = QtWidgets.QLineEdit(adm_visit_interface)
        self.stuid.setGeometry(QtCore.QRect(470, 80, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.stuid.setFont(font)
        self.stuid.setText("")
        self.stuid.setObjectName("stuid")

        self.retranslateUi(adm_visit_interface)
        self.query_reservation.clicked.connect(lambda x : find_record(adm_visit_interface))

    def retranslateUi(self, adm_visit_interface):
        _translate = QtCore.QCoreApplication.translate
        adm_visit_interface.setWindowTitle(_translate("adm_visit_interface", "查询预约"))
        self.label.setText(_translate("adm_visit_interface", "身份证号："))
        self.label_2.setText(_translate("adm_visit_interface", "姓名："))
        self.label_3.setText(_translate("adm_visit_interface", "联系方式："))
        self.label_4.setText(_translate("adm_visit_interface", "访问原因："))
        self.label_5.setText(_translate("adm_visit_interface", "访问时间："))
        self.label_6.setText(_translate("adm_visit_interface", "年"))
        self.label_7.setText(_translate("adm_visit_interface", "月"))
        self.label_8.setText(_translate("adm_visit_interface", "日"))
        self.query_reservation.setText(_translate("adm_visit_interface", "查询预约"))
        item = self.res_table.horizontalHeaderItem(0)
        item.setText(_translate("adm_visit_interface", "预约号"))
        item = self.res_table.horizontalHeaderItem(1)
        item.setText(_translate("adm_visit_interface", "访客姓名"))
        item = self.res_table.horizontalHeaderItem(2)
        item.setText(_translate("adm_visit_interface", "身份证号"))
        item = self.res_table.horizontalHeaderItem(3)
        item.setText(_translate("adm_visit_interface", "访客电话"))
        item = self.res_table.horizontalHeaderItem(4)
        item.setText(_translate("adm_visit_interface", "预约时间"))
        item = self.res_table.horizontalHeaderItem(5)
        item.setText(_translate("adm_visit_interface", "访问原因"))
        item = self.res_table.horizontalHeaderItem(6)
        item.setText(_translate("adm_visit_interface", "提交者"))
        self.label_10.setText(_translate("adm_visit_interface", "预约号："))
        self.label_9.setText(_translate("adm_visit_interface", "学生学号："))

def find_record(adm_visit_interface):
    query = QtSql.QSqlQuery()
    query_string = "select `reservation`.`resid`, `visitor`.`visid`, `visitor`.`name`, `visitor`.`telephone`, `reservation`.`reason`, `reservation`.`date`, `visitor`.`stuid` from `reservation`, `visitor`, `admin`, `student` where `reservation`.`visid` = `visitor`.`visid` and `reservation`.`stuid` = `visitor`.`stuid` and `student`.`stuid` = `reservation`.`stuid` and `admin`.`flatid` = `student`.`flatid` and `admin`.`admid` = :username and `reservation`.`date` >= curdate()"

    if(adm_visit_interface.ui.resid.text().isdigit()):
        query_string = query_string + " and `reservation`.`resid` = :resid"
    if(adm_visit_interface.ui.visid.text() != ''):
        query_string = query_string + " and `reservation`.`visid` like :visid"
    if(adm_visit_interface.ui.stuid.text() != ''):
        query_string = query_string + " and `reservation`.`stuid` like :stuid"
    if(adm_visit_interface.ui.name.text() != ''):
        query_string = query_string + " and `visitor`.`name` like :name"
    if(adm_visit_interface.ui.telephone.text() != ''):
        query_string = query_string + " and `visitor`.`telephone` like :telephone"
    if(adm_visit_interface.ui.year.text() != ''):
        query_string = query_string + " and year(`reservation`.`date`) = :year"
    if(adm_visit_interface.ui.month.text() != ''):
        query_string = query_string + " and month(`reservation`.`date`) = :month"
    if(adm_visit_interface.ui.day.text() != ''):
        query_string = query_string + " and day(`reservation`.`date`) = :day"
    if(adm_visit_interface.ui.reason.toPlainText() != ''):
        query_string = query_string + " and `reservation`.`reason` like :reason"

    query.prepare(query_string)
    query.bindValue(':username', adm_visit_interface.admid)
    if(adm_visit_interface.ui.resid.text().isdigit()):
        query.bindValue(':resid', int(adm_visit_interface.ui.resid.text()))
    query.bindValue(':visid', '%' + adm_visit_interface.ui.visid.text() + '%')
    query.bindValue(':stuid', '%' + adm_visit_interface.ui.stuid.text() + '%')
    query.bindValue(':name', '%' + adm_visit_interface.ui.name.text() + '%')
    query.bindValue(':telephone', '%' + adm_visit_interface.ui.telephone.text() + '%')
    query.bindValue(':year', adm_visit_interface.ui.year.text())
    query.bindValue(':month', adm_visit_interface.ui.month.text())
    query.bindValue(':day', adm_visit_interface.ui.day.text())
    query.bindValue(':reason', '%' + adm_visit_interface.ui.reason.toPlainText() + '%')
    query.exec()

    adm_visit_interface.ui.res_table.setRowCount(0)

    while query.next():
        adm_visit_interface.ui.res_table.insertRow(adm_visit_interface.ui.res_table.rowCount())
        i = adm_visit_interface.ui.res_table.rowCount() - 1
        adm_visit_interface.ui.res_table.setItem(i, 0, QtWidgets.QTableWidgetItem(str(query.value(0))))
        adm_visit_interface.ui.res_table.setItem(i, 1, QtWidgets.QTableWidgetItem(query.value(2)))
        adm_visit_interface.ui.res_table.setItem(i, 2, QtWidgets.QTableWidgetItem(query.value(1)))
        adm_visit_interface.ui.res_table.setItem(i, 3, QtWidgets.QTableWidgetItem(query.value(3)))
        adm_visit_interface.ui.res_table.setItem(i, 4, QtWidgets.QTableWidgetItem(query.value(4)))
        adm_visit_interface.ui.res_table.setItem(i, 5, QtWidgets.QTableWidgetItem(decode_date(query.value(5))))
        adm_visit_interface.ui.res_table.setItem(i, 6, QtWidgets.QTableWidgetItem(query.value(6)))