# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\linmou202\Programing\Compile_Files\Database_Basics\EP_2\src\frontend\ui\adm_info.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_adm_info_interface(object):
    def setupUi(self, adm_info_interface):
        adm_info_interface.setObjectName("adm_info_interface")
        adm_info_interface.resize(1358, 795)
        font = QtGui.QFont()
        font.setPointSize(12)
        adm_info_interface.setFont(font)
        self.table = QtWidgets.QTableWidget(adm_info_interface)
        self.table.setGeometry(QtCore.QRect(60, 50, 1231, 691))
        self.table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.table.setRowCount(0)
        self.table.setColumnCount(4)
        self.table.setObjectName("table")
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(3, item)
        self.table.verticalHeader().setVisible(False)

        self.retranslateUi(adm_info_interface)

    def retranslateUi(self, adm_info_interface):
        _translate = QtCore.QCoreApplication.translate
        adm_info_interface.setWindowTitle(_translate("adm_info_interface", "管理员信息"))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("adm_info_interface", "工号"))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("adm_info_interface", "姓名"))
        item = self.table.horizontalHeaderItem(2)
        item.setText(_translate("adm_info_interface", "电话"))
        item = self.table.horizontalHeaderItem(3)
        item.setText(_translate("adm_info_interface", "邮件"))
