# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\linmou202\Programing\Compile_Files\Database_Basics\EP_2\src\frontend\ui\admin.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets, QtSql
from ui.Ui_get_mtnc import Ui_get_mtnc_interface
from ui.Ui_adm_mtnc import Ui_adm_mtnc_interface
from ui.Ui_adm_visit import Ui_adm_visit_interface
from ui.Ui_dorm_info import Ui_dorm_info_interface
from utils.utils import *


class Ui_admin_interface(object):
    def setupUi(self, admin_interface, text):
        admin_interface.setObjectName("admin_interface")
        admin_interface.resize(727, 332)
        self.centralwidget = QtWidgets.QWidget(admin_interface)
        self.centralwidget.setGeometry(QtCore.QRect(0, 0, 701, 291))
        self.centralwidget.setObjectName("centralwidget")
        self.accept_maintenance = QtWidgets.QPushButton(self.centralwidget)
        self.accept_maintenance.setGeometry(QtCore.QRect(50, 102, 111, 61))
        self.accept_maintenance.setObjectName("accept_maintenance")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 40, 591, 16))
        self.label.setObjectName("label")
        self.complete_maintenance = QtWidgets.QPushButton(self.centralwidget)
        self.complete_maintenance.setGeometry(QtCore.QRect(50, 190, 111, 61))
        self.complete_maintenance.setObjectName("complete_maintenance")
        self.change_info = QtWidgets.QPushButton(self.centralwidget)
        self.change_info.setGeometry(QtCore.QRect(240, 190, 131, 61))
        self.change_info.setObjectName("change_info")
        self.change_dorm = QtWidgets.QPushButton(self.centralwidget)
        self.change_dorm.setGeometry(QtCore.QRect(240, 100, 131, 61))
        self.change_dorm.setObjectName("change_dorm")
        self.check_visitors = QtWidgets.QPushButton(self.centralwidget)
        self.check_visitors.setGeometry(QtCore.QRect(450, 100, 131, 61))
        self.check_visitors.setObjectName("check_visitors")
        self.statusbar = QtWidgets.QStatusBar(admin_interface)
        self.statusbar.setGeometry(QtCore.QRect(0, 0, 3, 18))
        self.statusbar.setObjectName("statusbar")

        self.retranslateUi(admin_interface, text)
        self.accept_maintenance.clicked.connect(lambda x : show_all_mtnc_interface(admin_interface))
        self.complete_maintenance.clicked.connect(lambda x : show_adm_mtnc_interface(admin_interface))
        self.check_visitors.clicked.connect(lambda x : show_adm_visit_interface(admin_interface))
        self.change_dorm.clicked.connect(lambda x : show_dorm_info_interface(admin_interface))

    def retranslateUi(self, admin_interface, text):
        _translate = QtCore.QCoreApplication.translate
        admin_interface.setWindowTitle(_translate("admin_interface", "管理员界面"))
        self.accept_maintenance.setText(_translate("admin_interface", "认领维修申请"))
        self.label.setText(_translate("admin_interface", text))
        self.complete_maintenance.setText(_translate("admin_interface", "管理接受的申请"))
        self.change_info.setText(_translate("admin_interface", "修改个人信息"))
        self.change_dorm.setText(_translate("admin_interface", "查看/管理住宿信息"))
        self.check_visitors.setText(_translate("admin_interface", "查询访客登记"))

def show_all_mtnc_interface(admin_interface):
    query = QtSql.QSqlQuery()
    query.prepare("select `maintenance`.`mtid`, `maintenance`.`request`, `maintenance`.`flatid`, `maintenance`.`roomid`, `maintenance`.`stuid`, `maintenance`.`subtime` from `maintenance`, `admin` where `maintenance`.`flatid` = `admin`.`flatid` and `maintenance`.`status` = 0 and `admin`.`admid` = :username")
    query.bindValue(':username', admin_interface.admid)
    query.exec()

    global get_mtnc_interface
    get_mtnc_interface = QtWidgets.QWidget()
    get_mtnc_interface.setAttribute(QtCore.Qt.WA_DeleteOnClose, True)
    get_mtnc_interface.ui = Ui_get_mtnc_interface()
    get_mtnc_interface.ui.setupUi(get_mtnc_interface)
    get_mtnc_interface.admid = admin_interface.admid

    while query.next():
        get_mtnc_interface.ui.table.insertRow(get_mtnc_interface.ui.table.rowCount())
        i = get_mtnc_interface.ui.table.rowCount() - 1
        get_mtnc_interface.ui.table.setItem(i, 0, QtWidgets.QTableWidgetItem(str(query.value(0))))
        get_mtnc_interface.ui.table.setItem(i, 1, QtWidgets.QTableWidgetItem(concat_address(query.value(2), query.value(3))))
        get_mtnc_interface.ui.table.setItem(i, 2, QtWidgets.QTableWidgetItem(query.value(1)))
        get_mtnc_interface.ui.table.setItem(i, 3, QtWidgets.QTableWidgetItem(decode_date(query.value(5))))
        get_mtnc_interface.ui.table.setItem(i, 4, QtWidgets.QTableWidgetItem(query.value(4)))

    get_mtnc_interface.show()

def show_adm_mtnc_interface(admin_interface):
    query = QtSql.QSqlQuery()
    query.prepare("select `mtid`, `request`, `flatid`, `roomid`, `stuid`, `subtime` from `maintenance` where `status` = 1 and `admid` = :username")
    query.bindValue(':username', admin_interface.admid)
    query.exec()

    global adm_mtnc_interface
    adm_mtnc_interface = QtWidgets.QWidget()
    adm_mtnc_interface.setAttribute(QtCore.Qt.WA_DeleteOnClose, True)
    adm_mtnc_interface.ui = Ui_adm_mtnc_interface()
    adm_mtnc_interface.ui.setupUi(adm_mtnc_interface)
    adm_mtnc_interface.admid = admin_interface.admid

    while query.next():
        adm_mtnc_interface.ui.table.insertRow(adm_mtnc_interface.ui.table.rowCount())
        i = adm_mtnc_interface.ui.table.rowCount() - 1
        adm_mtnc_interface.ui.table.setItem(i, 0, QtWidgets.QTableWidgetItem(str(query.value(0))))
        adm_mtnc_interface.ui.table.setItem(i, 1, QtWidgets.QTableWidgetItem(concat_address(query.value(2), query.value(3))))
        adm_mtnc_interface.ui.table.setItem(i, 2, QtWidgets.QTableWidgetItem(query.value(1)))
        adm_mtnc_interface.ui.table.setItem(i, 3, QtWidgets.QTableWidgetItem(decode_date(query.value(5))))
        adm_mtnc_interface.ui.table.setItem(i, 4, QtWidgets.QTableWidgetItem(query.value(4)))

    adm_mtnc_interface.show()

def show_adm_visit_interface(admin_interface):
    query = QtSql.QSqlQuery()
    query.prepare("select `reservation`.`resid`, `visitor`.`visid`, `visitor`.`name`, `visitor`.`telephone`, `reservation`.`reason`, `reservation`.`date`, `visitor`.`stuid` from `reservation`, `visitor`, `admin`, `student` where `reservation`.`visid` = `visitor`.`visid` and `reservation`.`stuid` = `visitor`.`stuid` and `student`.`stuid` = `reservation`.`stuid` and `admin`.`flatid` = `student`.`flatid` and `admin`.`admid` = :username and `reservation`.`date` >= curdate()")
    query.bindValue(':username', admin_interface.admid)
    query.exec()

    global adm_visit_interface
    adm_visit_interface = QtWidgets.QWidget()
    adm_visit_interface.setAttribute(QtCore.Qt.WA_DeleteOnClose, True)
    adm_visit_interface.ui = Ui_adm_visit_interface()
    adm_visit_interface.ui.setupUi(adm_visit_interface)
    adm_visit_interface.admid = admin_interface.admid

    while query.next():
        adm_visit_interface.ui.res_table.insertRow(adm_visit_interface.ui.res_table.rowCount())
        i = adm_visit_interface.ui.res_table.rowCount() - 1
        adm_visit_interface.ui.res_table.setItem(i, 0, QtWidgets.QTableWidgetItem(str(query.value(0))))
        adm_visit_interface.ui.res_table.setItem(i, 1, QtWidgets.QTableWidgetItem(query.value(2)))
        adm_visit_interface.ui.res_table.setItem(i, 2, QtWidgets.QTableWidgetItem(query.value(1)))
        adm_visit_interface.ui.res_table.setItem(i, 3, QtWidgets.QTableWidgetItem(query.value(3)))
        adm_visit_interface.ui.res_table.setItem(i, 4, QtWidgets.QTableWidgetItem(query.value(4)))
        adm_visit_interface.ui.res_table.setItem(i, 5, QtWidgets.QTableWidgetItem(decode_date(query.value(5))))
        adm_visit_interface.ui.res_table.setItem(i, 6, QtWidgets.QTableWidgetItem(query.value(6)))

    adm_visit_interface.show()

def show_dorm_info_interface(admin_interface):
    query = QtSql.QSqlQuery()
    query.prepare("select `flatid` from `admin` where `admid` = :username")
    query.bindValue(':username', admin_interface.admid)
    query.exec()
    query.next()
    flatid = query.value(0)

    global dorm_info_interface
    dorm_info_interface = QtWidgets.QWidget()
    dorm_info_interface.setAttribute(QtCore.Qt.WA_DeleteOnClose, True)
    dorm_info_interface.ui = Ui_dorm_info_interface()
    dorm_info_interface.ui.setupUi(dorm_info_interface)
    dorm_info_interface.flatid = flatid

    query.prepare("select `room`.`roomid`, `room`.`capacity`, count(*) from `room`, `student` where `student`.`roomid` = `room`.`roomid` and `student`.`flatid` = `room`.`flatid` and `room`.`flatid` = :flatid group by `room`.`roomid`, `room`.`capacity`")
    query.bindValue(':flatid', flatid)
    query.exec()

    while query.next():
        dorm_info_interface.ui.room_table.insertRow(dorm_info_interface.ui.room_table.rowCount())
        i = dorm_info_interface.ui.room_table.rowCount() - 1
        dorm_info_interface.ui.room_table.setItem(i, 0, QtWidgets.QTableWidgetItem(query.value(0)))
        dorm_info_interface.ui.room_table.setItem(i, 1, QtWidgets.QTableWidgetItem(str(query.value(1))))
        dorm_info_interface.ui.room_table.setItem(i, 2, QtWidgets.QTableWidgetItem(str(query.value(2))))
    
    query.prepare("select `stuid`, `name`, `telephone`, `email`, `roomid`, `bedid` from `student` where (`student`.`flatid` = :flatid or `student`.`flatid` is null)")
    query.bindValue(':flatid', flatid)
    query.exec()

    while query.next():
        dorm_info_interface.ui.stu_table.insertRow(dorm_info_interface.ui.stu_table.rowCount())
        i = dorm_info_interface.ui.stu_table.rowCount() - 1
        dorm_info_interface.ui.stu_table.setItem(i, 0, QtWidgets.QTableWidgetItem(query.value(0)))
        dorm_info_interface.ui.stu_table.setItem(i, 1, QtWidgets.QTableWidgetItem(query.value(1)))
        dorm_info_interface.ui.stu_table.setItem(i, 2, QtWidgets.QTableWidgetItem(query.value(2)))
        dorm_info_interface.ui.stu_table.setItem(i, 3, QtWidgets.QTableWidgetItem(query.value(3)))
        dorm_info_interface.ui.stu_table.setItem(i, 4, QtWidgets.QTableWidgetItem(query.value(4)))
        if (query.value(5) == 0):
            dorm_info_interface.ui.stu_table.setItem(i, 5, QtWidgets.QTableWidgetItem(''))
        else:
            dorm_info_interface.ui.stu_table.setItem(i, 5, QtWidgets.QTableWidgetItem(str(query.value(5))))
        
    dorm_info_interface.show()
