# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\linmou202\Programing\Compile_Files\Database_Basics\EP_2\src\frontend\ui\dorm_info.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets, QtSql
from utils.utils import *
from ui.Ui_error import Ui_error_box


class Ui_dorm_info_interface(object):
    def setupUi(self, dorm_info_interface):
        dorm_info_interface.setObjectName("dorm_info_interface")
        dorm_info_interface.resize(1354, 825)
        font = QtGui.QFont()
        font.setPointSize(12)
        dorm_info_interface.setFont(font)
        self.room_table = QtWidgets.QTableWidget(dorm_info_interface)
        self.room_table.setGeometry(QtCore.QRect(60, 350, 471, 431))
        self.room_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.room_table.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.room_table.setRowCount(0)
        self.room_table.setColumnCount(3)
        self.room_table.setObjectName("room_table")
        item = QtWidgets.QTableWidgetItem()
        self.room_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.room_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.room_table.setHorizontalHeaderItem(2, item)
        self.room_table.verticalHeader().setVisible(False)
        self.label = QtWidgets.QLabel(dorm_info_interface)
        self.label.setGeometry(QtCore.QRect(70, 90, 81, 31))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(dorm_info_interface)
        self.label_3.setGeometry(QtCore.QRect(70, 140, 81, 31))
        self.label_3.setObjectName("label_3")
        self.name = QtWidgets.QLineEdit(dorm_info_interface)
        self.name.setGeometry(QtCore.QRect(150, 90, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.name.setFont(font)
        self.name.setText("")
        self.name.setObjectName("name")
        self.roomid = QtWidgets.QLineEdit(dorm_info_interface)
        self.roomid.setGeometry(QtCore.QRect(150, 140, 211, 31))
        self.roomid.setObjectName("roomid")
        self.query_student = QtWidgets.QPushButton(dorm_info_interface)
        self.query_student.setGeometry(QtCore.QRect(1160, 110, 131, 61))
        self.query_student.setObjectName("query_student")
        self.stu_table = QtWidgets.QTableWidget(dorm_info_interface)
        self.stu_table.setGeometry(QtCore.QRect(550, 350, 741, 431))
        self.stu_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.stu_table.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.stu_table.setRowCount(0)
        self.stu_table.setColumnCount(6)
        self.stu_table.setObjectName("stu_table")
        item = QtWidgets.QTableWidgetItem()
        self.stu_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.stu_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.stu_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.stu_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.stu_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.stu_table.setHorizontalHeaderItem(5, item)
        self.stu_table.verticalHeader().setVisible(False)
        self.label_10 = QtWidgets.QLabel(dorm_info_interface)
        self.label_10.setGeometry(QtCore.QRect(70, 40, 81, 31))
        self.label_10.setObjectName("label_10")
        self.stuid = QtWidgets.QLineEdit(dorm_info_interface)
        self.stuid.setGeometry(QtCore.QRect(150, 40, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.stuid.setFont(font)
        self.stuid.setText("")
        self.stuid.setObjectName("stuid")
        self.assign_dorm = QtWidgets.QPushButton(dorm_info_interface)
        self.assign_dorm.setGeometry(QtCore.QRect(1160, 190, 131, 61))
        self.assign_dorm.setObjectName("assign_dorm")
        self.query_room = QtWidgets.QPushButton(dorm_info_interface)
        self.query_room.setGeometry(QtCore.QRect(1160, 30, 131, 61))
        self.query_room.setObjectName("query_room")
        self.cancel_dorm = QtWidgets.QPushButton(dorm_info_interface)
        self.cancel_dorm.setGeometry(QtCore.QRect(1160, 270, 131, 61))
        self.cancel_dorm.setObjectName("cancel_dorm")
        self.bedid = QtWidgets.QLineEdit(dorm_info_interface)
        self.bedid.setGeometry(QtCore.QRect(150, 190, 211, 31))
        self.bedid.setObjectName("bedid")
        self.label_4 = QtWidgets.QLabel(dorm_info_interface)
        self.label_4.setGeometry(QtCore.QRect(70, 190, 81, 31))
        self.label_4.setObjectName("label_4")

        self.retranslateUi(dorm_info_interface)
        self.query_room.clicked.connect(lambda x : find_room(dorm_info_interface))
        self.query_student.clicked.connect(lambda x : find_student(dorm_info_interface))
        self.assign_dorm.clicked.connect(lambda x : assign_dorm(dorm_info_interface))
        self.cancel_dorm.clicked.connect(lambda x : cancel_dorm(dorm_info_interface))

    def retranslateUi(self, dorm_info_interface):
        _translate = QtCore.QCoreApplication.translate
        dorm_info_interface.setWindowTitle(_translate("dorm_info_interface", "宿舍信息"))
        item = self.room_table.horizontalHeaderItem(0)
        item.setText(_translate("dorm_info_interface", "宿舍号"))
        item = self.room_table.horizontalHeaderItem(1)
        item.setText(_translate("dorm_info_interface", "最大容量"))
        item = self.room_table.horizontalHeaderItem(2)
        item.setText(_translate("dorm_info_interface", "居住人数"))
        self.label.setText(_translate("dorm_info_interface", "姓名："))
        self.label_3.setText(_translate("dorm_info_interface", "宿舍号："))
        self.query_student.setText(_translate("dorm_info_interface", "查询学生"))
        item = self.stu_table.horizontalHeaderItem(0)
        item.setText(_translate("dorm_info_interface", "学号"))
        item = self.stu_table.horizontalHeaderItem(1)
        item.setText(_translate("dorm_info_interface", "姓名"))
        item = self.stu_table.horizontalHeaderItem(2)
        item.setText(_translate("dorm_info_interface", "电话"))
        item = self.stu_table.horizontalHeaderItem(3)
        item.setText(_translate("dorm_info_interface", "邮箱"))
        item = self.stu_table.horizontalHeaderItem(4)
        item.setText(_translate("dorm_info_interface", "宿舍号"))
        item = self.stu_table.horizontalHeaderItem(5)
        item.setText(_translate("dorm_info_interface", "床位"))
        self.label_10.setText(_translate("dorm_info_interface", "学号："))
        self.assign_dorm.setText(_translate("dorm_info_interface", "分配宿舍"))
        self.query_room.setText(_translate("dorm_info_interface", "查询宿舍"))
        self.cancel_dorm.setText(_translate("dorm_info_interface", "取消学生的宿舍"))
        self.label_4.setText(_translate("dorm_info_interface", "床位："))

def find_room(dorm_info_interface):
    query = QtSql.QSqlQuery()
    query_string = "select `room`.`roomid`, `room`.`capacity`, count(*) from `room`, `student` where `student`.`roomid` = `room`.`roomid` and `student`.`flatid` = `room`.`flatid` and `room`.`flatid` = :flatid group by `room`.`roomid`, `room`.`capacity`"

    if(dorm_info_interface.ui.roomid.text() != ''):
        query_string = query_string + " having `room`.`roomid` like :roomid"

    query.prepare(query_string)
    query.bindValue(':flatid', dorm_info_interface.flatid)
    query.bindValue(':roomid', '%' + dorm_info_interface.ui.roomid.text() + '%')
    query.exec()

    dorm_info_interface.ui.room_table.setRowCount(0)
    
    while query.next():
        dorm_info_interface.ui.room_table.insertRow(dorm_info_interface.ui.room_table.rowCount())
        i = dorm_info_interface.ui.room_table.rowCount() - 1
        dorm_info_interface.ui.room_table.setItem(i, 0, QtWidgets.QTableWidgetItem(query.value(0)))
        dorm_info_interface.ui.room_table.setItem(i, 1, QtWidgets.QTableWidgetItem(str(query.value(1))))
        dorm_info_interface.ui.room_table.setItem(i, 2, QtWidgets.QTableWidgetItem(str(query.value(2))))

def find_student(dorm_info_interface):
    query = QtSql.QSqlQuery()
    query_string = "select `stuid`, `name`, `telephone`, `email`, `roomid`, `bedid` from `student` where (`student`.`flatid` = :flatid or `student`.`flatid` is null)"
    if(dorm_info_interface.ui.stuid.text() != ''):
        query_string = query_string + " and `stuid` like :stuid"
    if(dorm_info_interface.ui.name.text() != ''):
        query_string = query_string + " and `name` like :name"

    if(dorm_info_interface.ui.roomid.text() != ''):
        if(dorm_info_interface.ui.roomid.text() == "__NULL__"):
            query_string = query_string + " and `roomid` is null"
        else:
            query_string = query_string + " and `roomid` like :roomid"
            if(dorm_info_interface.ui.bedid.text() != ''):
                query_string = query_string + " and `bedid` like :bedid"

    query.prepare(query_string)
    query.bindValue(':flatid', dorm_info_interface.flatid)
    query.bindValue(':roomid', '%' + dorm_info_interface.ui.roomid.text() + '%')
    query.bindValue(':bedid', '%' + dorm_info_interface.ui.bedid.text() + '%')
    query.bindValue(':stuid', '%' + dorm_info_interface.ui.stuid.text() + '%')
    query.bindValue(':name', '%' + dorm_info_interface.ui.name.text() + '%')
    query.exec()

    dorm_info_interface.ui.stu_table.setRowCount(0)
    
    while query.next():
        dorm_info_interface.ui.stu_table.insertRow(dorm_info_interface.ui.stu_table.rowCount())
        i = dorm_info_interface.ui.stu_table.rowCount() - 1
        dorm_info_interface.ui.stu_table.setItem(i, 0, QtWidgets.QTableWidgetItem(query.value(0)))
        dorm_info_interface.ui.stu_table.setItem(i, 1, QtWidgets.QTableWidgetItem(query.value(1)))
        dorm_info_interface.ui.stu_table.setItem(i, 2, QtWidgets.QTableWidgetItem(query.value(2)))
        dorm_info_interface.ui.stu_table.setItem(i, 3, QtWidgets.QTableWidgetItem(query.value(3)))
        dorm_info_interface.ui.stu_table.setItem(i, 4, QtWidgets.QTableWidgetItem(query.value(4)))
        if (query.value(5) == 0):
            dorm_info_interface.ui.stu_table.setItem(i, 5, QtWidgets.QTableWidgetItem(''))
        else:
            dorm_info_interface.ui.stu_table.setItem(i, 5, QtWidgets.QTableWidgetItem(str(query.value(5))))

def assign_dorm(dorm_info_interface):
    if(dorm_info_interface.ui.stuid.text() == ''  or dorm_info_interface.ui.roomid.text() == ''  or not dorm_info_interface.ui.bedid.text().isdigit()):
        error_msgbox = QtWidgets.QDialog()
        error_msgbox.setAttribute(QtCore.Qt.WA_DeleteOnClose, True)
        error_msgbox.ui = Ui_error_box()
        error_msgbox.ui.setupUi(error_msgbox, "输入信息无效")
        error_msgbox.exec_()
    else:
        query = QtSql.QSqlQuery()
        query.prepare("call assign_dorm(:stuid, :flatid, :roomid, :bedid, @stat)")
        query.bindValue(':stuid', dorm_info_interface.ui.stuid.text())
        query.bindValue(':flatid', dorm_info_interface.flatid)
        query.bindValue(':roomid', dorm_info_interface.ui.roomid.text())
        query.bindValue(':bedid', int(dorm_info_interface.ui.bedid.text()))
        query.exec()
        query.exec("select @stat")
        query.next()

        if (query.value(0) > 0):
            error_msgbox = QtWidgets.QDialog()
            error_msgbox.setAttribute(QtCore.Qt.WA_DeleteOnClose, True)
            error_msgbox.ui = Ui_error_box()
            error_msgbox.ui.setupUi(error_msgbox, "无法更换宿舍")
            error_msgbox.exec_()
        else:
            find_room(dorm_info_interface)
            find_student(dorm_info_interface)

def cancel_dorm(dorm_info_interface):
    if(dorm_info_interface.ui.stuid.text() == ''):
        error_msgbox = QtWidgets.QDialog()
        error_msgbox.setAttribute(QtCore.Qt.WA_DeleteOnClose, True)
        error_msgbox.ui = Ui_error_box()
        error_msgbox.ui.setupUi(error_msgbox, "必须输入学生学号")
        error_msgbox.exec_()
    else:
        query = QtSql.QSqlQuery()
        query.prepare("call cancel_dorm(:stuid, :flatid, @stat)")
        query.bindValue(':stuid', dorm_info_interface.ui.stuid.text())
        query.bindValue(':flatid', dorm_info_interface.flatid)
        query.exec()
        query.exec("select @stat")
        query.next()

        if (query.value(0) > 0):
            error_msgbox = QtWidgets.QDialog()
            error_msgbox.setAttribute(QtCore.Qt.WA_DeleteOnClose, True)
            error_msgbox.ui = Ui_error_box()
            error_msgbox.ui.setupUi(error_msgbox, "无法将该学生移出宿舍")
            error_msgbox.exec_()
        else:
            find_room(dorm_info_interface)
            find_student(dorm_info_interface)