# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\linmou202\Programing\Compile_Files\Database_Basics\EP_2\src\frontend\ui\error.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_error_box(object):
    def setupUi(self, error_box, error_info):
        error_box.setObjectName("error_box")
        error_box.resize(316, 149)
        self.error_info = QtWidgets.QLabel(error_box)
        self.error_info.setGeometry(QtCore.QRect(20, 30, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        self.error_info.setFont(font)
        self.error_info.setFocusPolicy(QtCore.Qt.NoFocus)
        self.error_info.setTextFormat(QtCore.Qt.PlainText)
        self.error_info.setScaledContents(False)
        self.error_info.setAlignment(QtCore.Qt.AlignCenter)
        self.error_info.setObjectName("error_info")
        self.return_button = QtWidgets.QPushButton(error_box)
        self.return_button.setGeometry(QtCore.QRect(120, 90, 75, 23))
        self.return_button.setObjectName("return_button")
        self.return_button.clicked.connect(error_box.close)

        self.retranslateUi(error_box, error_info)

    def retranslateUi(self, error_box, error_info):
        _translate = QtCore.QCoreApplication.translate
        error_box.setWindowTitle(_translate("error_box", "错误"))
        self.error_info.setText(_translate("error_box", error_info))
        self.return_button.setText(_translate("error_box", "返回"))
