# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\linmou202\Programing\Compile_Files\Database_Basics\EP_2\src\frontend\ui\login.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets, QtSql
from ui.Ui_student import Ui_student_interface
from ui.Ui_admin import Ui_admin_interface
from ui.Ui_error import Ui_error_box


class Ui_login_interface(object):
    def setupUi(self, login):
        login.setObjectName("login")
        login.resize(796, 232)
        self.login_button = QtWidgets.QPushButton(login)
        self.login_button.setGeometry(QtCore.QRect(594, 51, 141, 111))
        self.login_button.setObjectName("login_button")
        self.label_2 = QtWidgets.QLabel(login)
        self.label_2.setGeometry(QtCore.QRect(64, 121, 31, 31))
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(login)
        self.label.setGeometry(QtCore.QRect(34, 71, 61, 31))
        self.label.setObjectName("label")
        self.password = QtWidgets.QLineEdit(login)
        self.password.setGeometry(QtCore.QRect(100, 120, 481, 31))
        self.password.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.password.setText("")
        self.password.setObjectName("password")
        self.username = QtWidgets.QLineEdit(login)
        self.username.setGeometry(QtCore.QRect(100, 70, 481, 31))
        self.username.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.username.setObjectName("username")

        self.retranslateUi(login)
        self.login_button.clicked.connect(lambda x : try_login(login))

    def retranslateUi(self, login):
        _translate = QtCore.QCoreApplication.translate
        login.setWindowTitle(_translate("login", "登录界面"))
        self.login_button.setText(_translate("login", "登录"))
        self.username.setText(_translate("login", "A001"))
        self.label_2.setText(_translate("login", "密码："))
        self.password.setText(_translate("login", "alice"))
        self.label.setText(_translate("login", "学号/工号："))

def try_login(login_interface):
    username = login_interface.ui.username.text()
    password = login_interface.ui.password.text()

    query = QtSql.QSqlQuery()
    query.prepare("call find_account(:username, :password, @ac_type)")
    query.bindValue(':username', username)
    query.bindValue(':password', password)
    query.exec()
    query.exec("select @ac_type")
    query.next()

    if (query.value(0) == 1):
        info_query = QtSql.QSqlQuery()
        info_query.prepare("select `name`, `flatid` from `admin` where `admid` = :username")
        info_query.bindValue(':username', username)
        info_query.exec()
        info_query.next()

        global admin_interface
        admin_interface = QtWidgets.QMainWindow()
        admin_interface.setAttribute(QtCore.Qt.WA_DeleteOnClose, True)
        admin_interface.ui = Ui_admin_interface()
        admin_interface.ui.setupUi(admin_interface, f"欢迎, 公寓 {info_query.value(1)} 的管理员 {info_query.value(0)}.")
        admin_interface.show()
        admin_interface.admid = username
        login_interface.close()
    
    elif (query.value(0) == 2):
        info_query = QtSql.QSqlQuery()
        info_query.prepare("select `name`, `roomid`, `flatid`, `bedid` from `student` where `stuid` = :username")
        info_query.bindValue(':username', username)
        info_query.exec()
        info_query.next()

        global student_interface
        student_interface = QtWidgets.QMainWindow()
        student_interface.setAttribute(QtCore.Qt.WA_DeleteOnClose, True)
        student_interface.ui = Ui_student_interface()
        student_interface.ui.setupUi(student_interface, f"欢迎, {info_query.value(0)}. 你的宿舍位于公寓 {info_query.value(2)} 的 {info_query.value(1)} 号房间, 床位为 {info_query.value(3)}.")
        student_interface.stuid = username
        student_interface.show()
        login_interface.close()
    
    else:
        error_msgbox = QtWidgets.QDialog()
        error_msgbox.setAttribute(QtCore.Qt.WA_DeleteOnClose, True)
        error_msgbox.ui = Ui_error_box()
        error_msgbox.ui.setupUi(error_msgbox, "用户名或密码无效")
        error_msgbox.exec_()