# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\linmou202\Programing\Compile_Files\Database_Basics\EP_2\src\frontend\ui\student.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets, QtSql
from ui.Ui_stu_mtnc import Ui_stu_mtnc_interface
from ui.Ui_stu_visit import Ui_stu_visit_interface
from ui.Ui_adm_info import Ui_adm_info_interface

from utils.utils import *


class Ui_student_interface(object):
    def setupUi(self, student_interface, text):
        student_interface.setObjectName("student_interface")
        student_interface.resize(622, 332)
        self.centralwidget = QtWidgets.QWidget(student_interface)
        self.centralwidget.setObjectName("centralwidget")
        self.ask_maintenance = QtWidgets.QPushButton(self.centralwidget)
        self.ask_maintenance.setGeometry(QtCore.QRect(50, 102, 131, 61))
        self.ask_maintenance.setObjectName("ask_maintenance")
        self.student_info = QtWidgets.QLabel(self.centralwidget)
        self.student_info.setGeometry(QtCore.QRect(60, 40, 591, 16))
        self.student_info.setObjectName("student_info")
        self.add_visitor = QtWidgets.QPushButton(self.centralwidget)
        self.add_visitor.setGeometry(QtCore.QRect(230, 100, 121, 61))
        self.add_visitor.setObjectName("add_visitor")
        self.check_admin = QtWidgets.QPushButton(self.centralwidget)
        self.check_admin.setGeometry(QtCore.QRect(50, 190, 131, 61))
        self.check_admin.setObjectName("check_admin")
        self.change_info = QtWidgets.QPushButton(self.centralwidget)
        self.change_info.setGeometry(QtCore.QRect(230, 190, 121, 61))
        self.change_info.setObjectName("change_info")
        student_interface.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(student_interface)
        self.statusbar.setObjectName("statusbar")
        student_interface.setStatusBar(self.statusbar)

        self.retranslateUi(student_interface, text)
        self.ask_maintenance.clicked.connect(lambda x : show_stu_mtnc_interface(student_interface))
        self.add_visitor.clicked.connect(lambda x : show_stu_visit_interface(student_interface))
        self.check_admin.clicked.connect(lambda x : show_admin_information(student_interface))

    def retranslateUi(self, student_interface, text):
        _translate = QtCore.QCoreApplication.translate
        student_interface.setWindowTitle(_translate("student_interface", "学生界面"))
        self.ask_maintenance.setText(_translate("student_interface", "维修信息管理"))
        self.student_info.setText(_translate("student_interface", text))
        self.add_visitor.setText(_translate("student_interface", "访问信息管理"))
        self.check_admin.setText(_translate("student_interface", "查看管理员信息"))
        self.change_info.setText(_translate("student_interface", "更改个人信息"))

def show_stu_mtnc_interface(student_interface):
    query = QtSql.QSqlQuery()
    query.prepare("select `mtid`, `request`, `status`, `flatid`, `roomid`, `subtime`, `admid`, `fintime` from `maintenance` where `stuid` = :username")
    query.bindValue(':username', student_interface.stuid)
    query.exec()

    global stu_mtnc_interface
    stu_mtnc_interface = QtWidgets.QWidget()
    stu_mtnc_interface.setAttribute(QtCore.Qt.WA_DeleteOnClose, True)
    stu_mtnc_interface.ui = Ui_stu_mtnc_interface()
    stu_mtnc_interface.ui.setupUi(stu_mtnc_interface)
    stu_mtnc_interface.stuid = student_interface.stuid

    while query.next():
        stu_mtnc_interface.ui.table.insertRow(stu_mtnc_interface.ui.table.rowCount())
        i = stu_mtnc_interface.ui.table.rowCount() - 1
        stu_mtnc_interface.ui.table.setItem(i, 0, QtWidgets.QTableWidgetItem(str(query.value(0))))
        stu_mtnc_interface.ui.table.setItem(i, 1, QtWidgets.QTableWidgetItem(concat_address(query.value(3), query.value(4))))
        stu_mtnc_interface.ui.table.setItem(i, 2, QtWidgets.QTableWidgetItem(decode_status(query.value(2))))
        stu_mtnc_interface.ui.table.setItem(i, 3, QtWidgets.QTableWidgetItem(query.value(1)))
        stu_mtnc_interface.ui.table.setItem(i, 4, QtWidgets.QTableWidgetItem(decode_date(query.value(5))))
        stu_mtnc_interface.ui.table.setItem(i, 5, QtWidgets.QTableWidgetItem(query.value(6)))
        stu_mtnc_interface.ui.table.setItem(i, 6, QtWidgets.QTableWidgetItem(decode_date(query.value(7))))

    stu_mtnc_interface.show()

def show_stu_visit_interface(student_interface):
    global stu_visitor_interface
    stu_visitor_interface = QtWidgets.QWidget()
    stu_visitor_interface.setAttribute(QtCore.Qt.WA_DeleteOnClose, True)
    stu_visitor_interface.ui = Ui_stu_visit_interface()
    stu_visitor_interface.ui.setupUi(stu_visitor_interface)
    stu_visitor_interface.stuid = student_interface.stuid

    query = QtSql.QSqlQuery()
    query.prepare("select `visid`, `name`, `telephone` from `visitor` where `stuid` = :username")
    query.bindValue(':username', student_interface.stuid)
    query.exec()
    while query.next():
        stu_visitor_interface.ui.visitor_table.insertRow(stu_visitor_interface.ui.visitor_table.rowCount())
        i = stu_visitor_interface.ui.visitor_table.rowCount() - 1
        stu_visitor_interface.ui.visitor_table.setItem(i, 0, QtWidgets.QTableWidgetItem(query.value(0)))
        stu_visitor_interface.ui.visitor_table.setItem(i, 1, QtWidgets.QTableWidgetItem(query.value(1)))
        stu_visitor_interface.ui.visitor_table.setItem(i, 2, QtWidgets.QTableWidgetItem(query.value(2)))

    query.prepare("select `resid`, `visid`, `date`, `reason` from `reservation` where `stuid` = :username and `date` >= curdate()")
    query.bindValue(':username', student_interface.stuid)
    query.exec()
    while query.next():
        stu_visitor_interface.ui.res_table.insertRow(stu_visitor_interface.ui.res_table.rowCount())
        i = stu_visitor_interface.ui.res_table.rowCount() - 1
        stu_visitor_interface.ui.res_table.setItem(i, 0, QtWidgets.QTableWidgetItem(str(query.value(0))))
        stu_visitor_interface.ui.res_table.setItem(i, 1, QtWidgets.QTableWidgetItem(query.value(1)))
        stu_visitor_interface.ui.res_table.setItem(i, 2, QtWidgets.QTableWidgetItem(decode_date(query.value(2))))
        stu_visitor_interface.ui.res_table.setItem(i, 3, QtWidgets.QTableWidgetItem(query.value(3)))

    stu_visitor_interface.show()

def show_admin_information(student_interface):
    query = QtSql.QSqlQuery()
    query.prepare("select `admin`.`admid`, `admin`.`name`, `admin`.`telephone`, `admin`.`email` from `admin`, `student` where `admin`.`flatid` = `student`.`flatid` and `stuid` = :username")
    query.bindValue(':username', student_interface.stuid)
    query.exec()

    global adm_info_interface
    adm_info_interface = QtWidgets.QWidget()
    adm_info_interface.setAttribute(QtCore.Qt.WA_DeleteOnClose, True)
    adm_info_interface.ui = Ui_adm_info_interface()
    adm_info_interface.ui.setupUi(adm_info_interface)

    while query.next():
        adm_info_interface.ui.table.insertRow(adm_info_interface.ui.table.rowCount())
        i = adm_info_interface.ui.table.rowCount() - 1
        adm_info_interface.ui.table.setItem(i, 0, QtWidgets.QTableWidgetItem(query.value(0)))
        adm_info_interface.ui.table.setItem(i, 1, QtWidgets.QTableWidgetItem(query.value(1)))
        adm_info_interface.ui.table.setItem(i, 2, QtWidgets.QTableWidgetItem(query.value(2)))
        adm_info_interface.ui.table.setItem(i, 3, QtWidgets.QTableWidgetItem(query.value(3)))

    adm_info_interface.show()