# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\linmou202\Programing\Compile_Files\Database_Basics\EP_2\src\frontend\ui\stu_visit.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets, QtSql
from utils.utils import *
from ui.Ui_error import Ui_error_box


class Ui_stu_visit_interface(object):
    def setupUi(self, stu_visit_interface):
        stu_visit_interface.setObjectName("stu_visit_interface")
        stu_visit_interface.resize(1354, 825)
        font = QtGui.QFont()
        font.setPointSize(12)
        stu_visit_interface.setFont(font)
        self.visitor_table = QtWidgets.QTableWidget(stu_visit_interface)
        self.visitor_table.setGeometry(QtCore.QRect(60, 350, 471, 431))
        self.visitor_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.visitor_table.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.visitor_table.setRowCount(0)
        self.visitor_table.setColumnCount(3)
        self.visitor_table.setObjectName("visitor_table")
        item = QtWidgets.QTableWidgetItem()
        self.visitor_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.visitor_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.visitor_table.setHorizontalHeaderItem(2, item)
        self.visitor_table.verticalHeader().setVisible(False)
        self.label = QtWidgets.QLabel(stu_visit_interface)
        self.label.setGeometry(QtCore.QRect(70, 80, 81, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(stu_visit_interface)
        self.label_2.setGeometry(QtCore.QRect(70, 120, 81, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(stu_visit_interface)
        self.label_3.setGeometry(QtCore.QRect(70, 160, 81, 31))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(stu_visit_interface)
        self.label_4.setGeometry(QtCore.QRect(70, 240, 71, 31))
        self.label_4.setObjectName("label_4")
        self.add_visitor = QtWidgets.QPushButton(stu_visit_interface)
        self.add_visitor.setGeometry(QtCore.QRect(1010, 110, 131, 61))
        self.add_visitor.setObjectName("add_visitor")
        self.label_5 = QtWidgets.QLabel(stu_visit_interface)
        self.label_5.setGeometry(QtCore.QRect(70, 200, 81, 31))
        self.label_5.setObjectName("label_5")
        self.visid = QtWidgets.QLineEdit(stu_visit_interface)
        self.visid.setGeometry(QtCore.QRect(150, 80, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.visid.setFont(font)
        self.visid.setText("")
        self.visid.setObjectName("visid")
        self.name = QtWidgets.QLineEdit(stu_visit_interface)
        self.name.setGeometry(QtCore.QRect(150, 120, 211, 31))
        self.name.setObjectName("name")
        self.telephone = QtWidgets.QLineEdit(stu_visit_interface)
        self.telephone.setGeometry(QtCore.QRect(150, 160, 211, 31))
        self.telephone.setObjectName("telephone")
        self.year = QtWidgets.QLineEdit(stu_visit_interface)
        self.year.setGeometry(QtCore.QRect(150, 200, 51, 31))
        self.year.setText("")
        self.year.setObjectName("year")
        self.label_6 = QtWidgets.QLabel(stu_visit_interface)
        self.label_6.setGeometry(QtCore.QRect(210, 200, 21, 31))
        self.label_6.setObjectName("label_6")
        self.month = QtWidgets.QLineEdit(stu_visit_interface)
        self.month.setGeometry(QtCore.QRect(230, 200, 41, 31))
        self.month.setText("")
        self.month.setObjectName("month")
        self.label_7 = QtWidgets.QLabel(stu_visit_interface)
        self.label_7.setGeometry(QtCore.QRect(280, 200, 21, 31))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(stu_visit_interface)
        self.label_8.setGeometry(QtCore.QRect(350, 200, 21, 31))
        self.label_8.setObjectName("label_8")
        self.day = QtWidgets.QLineEdit(stu_visit_interface)
        self.day.setGeometry(QtCore.QRect(300, 200, 41, 31))
        self.day.setText("")
        self.day.setObjectName("day")
        self.label_9 = QtWidgets.QLabel(stu_visit_interface)
        self.label_9.setGeometry(QtCore.QRect(70, 260, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.query_reservation = QtWidgets.QPushButton(stu_visit_interface)
        self.query_reservation.setGeometry(QtCore.QRect(1160, 30, 131, 61))
        self.query_reservation.setObjectName("query_reservation")
        self.reason = QtWidgets.QPlainTextEdit(stu_visit_interface)
        self.reason.setGeometry(QtCore.QRect(150, 240, 801, 91))
        self.reason.setPlainText("")
        self.reason.setObjectName("reason")
        self.cancel_reservation = QtWidgets.QPushButton(stu_visit_interface)
        self.cancel_reservation.setGeometry(QtCore.QRect(1160, 270, 131, 61))
        self.cancel_reservation.setObjectName("cancel_reservation")
        self.res_table = QtWidgets.QTableWidget(stu_visit_interface)
        self.res_table.setGeometry(QtCore.QRect(550, 350, 741, 431))
        self.res_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.res_table.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.res_table.setRowCount(0)
        self.res_table.setColumnCount(4)
        self.res_table.setObjectName("res_table")
        item = QtWidgets.QTableWidgetItem()
        self.res_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.res_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.res_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.res_table.setHorizontalHeaderItem(3, item)
        self.res_table.verticalHeader().setVisible(False)
        self.label_10 = QtWidgets.QLabel(stu_visit_interface)
        self.label_10.setGeometry(QtCore.QRect(70, 40, 81, 31))
        self.label_10.setObjectName("label_10")
        self.resid = QtWidgets.QLineEdit(stu_visit_interface)
        self.resid.setGeometry(QtCore.QRect(150, 40, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.resid.setFont(font)
        self.resid.setText("")
        self.resid.setObjectName("resid")
        self.delete_visitor = QtWidgets.QPushButton(stu_visit_interface)
        self.delete_visitor.setGeometry(QtCore.QRect(1010, 270, 131, 61))
        self.delete_visitor.setObjectName("delete_visitor")
        self.add_reservation = QtWidgets.QPushButton(stu_visit_interface)
        self.add_reservation.setGeometry(QtCore.QRect(1160, 110, 131, 61))
        self.add_reservation.setObjectName("add_reservation")
        self.query_visitor = QtWidgets.QPushButton(stu_visit_interface)
        self.query_visitor.setGeometry(QtCore.QRect(1010, 30, 131, 61))
        self.query_visitor.setObjectName("query_visitor")
        self.alter_reservation = QtWidgets.QPushButton(stu_visit_interface)
        self.alter_reservation.setGeometry(QtCore.QRect(1160, 190, 131, 61))
        self.alter_reservation.setObjectName("alter_reservation")
        self.alter_visitor = QtWidgets.QPushButton(stu_visit_interface)
        self.alter_visitor.setGeometry(QtCore.QRect(1010, 190, 131, 61))
        self.alter_visitor.setObjectName("alter_visitor")
        self.label_11 = QtWidgets.QLabel(stu_visit_interface)
        self.label_11.setGeometry(QtCore.QRect(660, 200, 81, 31))
        self.label_11.setObjectName("label_11")
        self.ori_visid = QtWidgets.QLineEdit(stu_visit_interface)
        self.ori_visid.setGeometry(QtCore.QRect(740, 200, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.ori_visid.setFont(font)
        self.ori_visid.setText("")
        self.ori_visid.setObjectName("ori_visid")

        self.retranslateUi(stu_visit_interface)
        self.query_visitor.clicked.connect(lambda x : find_visitor(stu_visit_interface))
        self.add_visitor.clicked.connect(lambda x : add_visitor(stu_visit_interface))
        self.alter_visitor.clicked.connect(lambda x : update_visitor(stu_visit_interface))
        self.delete_visitor.clicked.connect(lambda x : delete_visitor(stu_visit_interface))

        self.query_reservation.clicked.connect(lambda x : find_reservation(stu_visit_interface))
        self.add_reservation.clicked.connect(lambda x : add_reservation(stu_visit_interface))
        self.alter_reservation.clicked.connect(lambda x : update_reservation(stu_visit_interface))
        self.cancel_reservation.clicked.connect(lambda x : delete_reservation(stu_visit_interface))

    def retranslateUi(self, stu_visit_interface):
        _translate = QtCore.QCoreApplication.translate
        stu_visit_interface.setWindowTitle(_translate("stu_visit_interface", "访问预约"))
        item = self.visitor_table.horizontalHeaderItem(0)
        item.setText(_translate("stu_visit_interface", "身份证号"))
        item = self.visitor_table.horizontalHeaderItem(1)
        item.setText(_translate("stu_visit_interface", "姓名"))
        item = self.visitor_table.horizontalHeaderItem(2)
        item.setText(_translate("stu_visit_interface", "联系方式"))
        self.label.setText(_translate("stu_visit_interface", "身份证号："))
        self.label_2.setText(_translate("stu_visit_interface", "姓名："))
        self.label_3.setText(_translate("stu_visit_interface", "联系方式："))
        self.label_4.setText(_translate("stu_visit_interface", "访问原因："))
        self.add_visitor.setText(_translate("stu_visit_interface", "添加访客"))
        self.label_5.setText(_translate("stu_visit_interface", "访问时间："))
        self.label_6.setText(_translate("stu_visit_interface", "年"))
        self.label_7.setText(_translate("stu_visit_interface", "月"))
        self.label_8.setText(_translate("stu_visit_interface", "日"))
        self.label_9.setText(_translate("stu_visit_interface", "(100字以内)"))
        self.query_reservation.setText(_translate("stu_visit_interface", "查询预约"))
        self.cancel_reservation.setText(_translate("stu_visit_interface", "取消预约"))
        item = self.res_table.horizontalHeaderItem(0)
        item.setText(_translate("stu_visit_interface", "预约号"))
        item = self.res_table.horizontalHeaderItem(1)
        item.setText(_translate("stu_visit_interface", "身份证号"))
        item = self.res_table.horizontalHeaderItem(2)
        item.setText(_translate("stu_visit_interface", "预约时间"))
        item = self.res_table.horizontalHeaderItem(3)
        item.setText(_translate("stu_visit_interface", "访问原因"))
        self.label_10.setText(_translate("stu_visit_interface", "预约号："))
        self.delete_visitor.setText(_translate("stu_visit_interface", "删除访客"))
        self.add_reservation.setText(_translate("stu_visit_interface", "提交预约"))
        self.query_visitor.setText(_translate("stu_visit_interface", "查询访客"))
        self.alter_reservation.setText(_translate("stu_visit_interface", "修改预约"))
        self.alter_visitor.setText(_translate("stu_visit_interface", "修改信息"))
        self.label_11.setText(_translate("stu_visit_interface", "身份证号："))

def find_visitor(stu_visit_interface):
    query = QtSql.QSqlQuery()
    query_string = "select `visid`, `name`, `telephone` from `visitor` where `stuid` = :username"

    if(stu_visit_interface.ui.visid.text() != ''):
        query_string = query_string + " and `visid` like :visid"
    if(stu_visit_interface.ui.name.text() != ''):
        query_string = query_string + " and `name` like :name"
    if(stu_visit_interface.ui.telephone.text() != ''):
        query_string = query_string + " and `telephone` like :telephone"

    query.prepare(query_string)
    query.bindValue(':username', stu_visit_interface.stuid)
    query.bindValue(':visid', '%' + stu_visit_interface.ui.visid.text() + '%')
    query.bindValue(':name', '%' + stu_visit_interface.ui.name.text() + '%')
    query.bindValue(':telephone', '%' + stu_visit_interface.ui.telephone.text() + '%')
    query.exec()

    stu_visit_interface.ui.visitor_table.setRowCount(0)
    
    while query.next():
        stu_visit_interface.ui.visitor_table.insertRow(stu_visit_interface.ui.visitor_table.rowCount())
        i = stu_visit_interface.ui.visitor_table.rowCount() - 1
        stu_visit_interface.ui.visitor_table.setItem(i, 0, QtWidgets.QTableWidgetItem(query.value(0)))
        stu_visit_interface.ui.visitor_table.setItem(i, 1, QtWidgets.QTableWidgetItem(query.value(1)))
        stu_visit_interface.ui.visitor_table.setItem(i, 2, QtWidgets.QTableWidgetItem(query.value(2)))

def add_visitor(stu_visit_interface):
    if(stu_visit_interface.ui.visid.text() == '' or stu_visit_interface.ui.name.text() == '' or stu_visit_interface.ui.telephone.text() == ''):
        error_msgbox = QtWidgets.QDialog()
        error_msgbox.setAttribute(QtCore.Qt.WA_DeleteOnClose, True)
        error_msgbox.ui = Ui_error_box()
        error_msgbox.ui.setupUi(error_msgbox, "必须提供完整信息")
        error_msgbox.exec_()
    else:
        query = QtSql.QSqlQuery()
        query.prepare("call add_visitor(:username, :visid, :name, :telephone, @stat)")
        query.bindValue(':username', stu_visit_interface.stuid)
        query.bindValue(':visid', stu_visit_interface.ui.visid.text())
        query.bindValue(':name', stu_visit_interface.ui.name.text())
        query.bindValue(':telephone', stu_visit_interface.ui.telephone.text())
        query.exec()
        query.exec("select @stat")
        query.next()

        if (query.value(0) > 0):
            error_msgbox = QtWidgets.QDialog()
            error_msgbox.setAttribute(QtCore.Qt.WA_DeleteOnClose, True)
            error_msgbox.ui = Ui_error_box()
            error_msgbox.ui.setupUi(error_msgbox, f"无法新增该访客信息")
            error_msgbox.exec_()
        else:
            find_visitor(stu_visit_interface)

def update_visitor(stu_visit_interface):
    if(stu_visit_interface.ui.ori_visid.text() == ''):
        error_msgbox = QtWidgets.QDialog()
        error_msgbox.setAttribute(QtCore.Qt.WA_DeleteOnClose, True)
        error_msgbox.ui = Ui_error_box()
        error_msgbox.ui.setupUi(error_msgbox, "目标身份证号不能为空")
        error_msgbox.exec_()
    else:
        query = QtSql.QSqlQuery()
        query.prepare("call update_visitor(:username, :visid, :name, :telephone, :ori_visid, @stat)")
        query.bindValue(':username', stu_visit_interface.stuid)
        query.bindValue(':visid', stu_visit_interface.ui.visid.text())
        query.bindValue(':name', stu_visit_interface.ui.name.text())
        query.bindValue(':telephone', stu_visit_interface.ui.telephone.text())
        query.bindValue(':ori_visid', stu_visit_interface.ui.ori_visid.text())
        query.exec()
        query.exec("select @stat")
        query.next()

        if (query.value(0) > 0):
            error_msgbox = QtWidgets.QDialog()
            error_msgbox.setAttribute(QtCore.Qt.WA_DeleteOnClose, True)
            error_msgbox.ui = Ui_error_box()
            error_msgbox.ui.setupUi(error_msgbox, f"访客信息更新失败")
            error_msgbox.exec_()
        else:
            find_visitor(stu_visit_interface)
            find_reservation(stu_visit_interface)

def delete_visitor(stu_visit_interface):
    if(stu_visit_interface.ui.visid.text() == ''):
        error_msgbox = QtWidgets.QDialog()
        error_msgbox.setAttribute(QtCore.Qt.WA_DeleteOnClose, True)
        error_msgbox.ui = Ui_error_box()
        error_msgbox.ui.setupUi(error_msgbox, "目标身份证号不能为空")
        error_msgbox.exec_()
    else:
        query = QtSql.QSqlQuery()
        query.prepare("call delete_visitor(:username, :visid, @stat)")
        query.bindValue(':username', stu_visit_interface.stuid)
        query.bindValue(':visid', stu_visit_interface.ui.visid.text())
        query.exec()
        query.exec("select @stat")
        query.next()

        if (query.value(0) > 0):
            error_msgbox = QtWidgets.QDialog()
            error_msgbox.setAttribute(QtCore.Qt.WA_DeleteOnClose, True)
            error_msgbox.ui = Ui_error_box()
            error_msgbox.ui.setupUi(error_msgbox, "访客信息删除失败")
            error_msgbox.exec_()
        else:
            find_visitor(stu_visit_interface)
            find_reservation(stu_visit_interface)

def find_reservation(stu_visit_interface):
    query = QtSql.QSqlQuery()
    query_string = "select `resid`, `visid`, `date`, `reason` from `reservation` where `stuid` = :username and `date` >= curdate()"

    if(stu_visit_interface.ui.resid.text().isdigit()):
        query_string = query_string + " and `resid` = :resid"
    if(stu_visit_interface.ui.visid.text() != ''):
        query_string = query_string + " and `visid` like :visid"
    if(stu_visit_interface.ui.year.text() != ''):
        query_string = query_string + " and year(`date`) = :year"
    if(stu_visit_interface.ui.month.text() != ''):
        query_string = query_string + " and month(`date`) = :month"
    if(stu_visit_interface.ui.day.text() != ''):
        query_string = query_string + " and day(`date`) = :day"
    if(stu_visit_interface.ui.reason.toPlainText() != ''):
        query_string = query_string + " and `reason` like :reason"

    query.prepare(query_string)
    query.bindValue(':username', stu_visit_interface.stuid)
    if(stu_visit_interface.ui.resid.text() != '' and stu_visit_interface.ui.resid.text().isdigit()):
        query.bindValue(':resid', int(stu_visit_interface.ui.resid.text()))
    query.bindValue(':visid', '%' + stu_visit_interface.ui.visid.text() + '%')
    query.bindValue(':year', stu_visit_interface.ui.year.text())
    query.bindValue(':month', stu_visit_interface.ui.month.text())
    query.bindValue(':day', stu_visit_interface.ui.day.text())
    query.bindValue(':reason', '%' + stu_visit_interface.ui.reason.toPlainText() + '%')
    query.exec()

    stu_visit_interface.ui.res_table.setRowCount(0)
    
    while query.next():
        stu_visit_interface.ui.res_table.insertRow(stu_visit_interface.ui.res_table.rowCount())
        i = stu_visit_interface.ui.res_table.rowCount() - 1
        stu_visit_interface.ui.res_table.setItem(i, 0, QtWidgets.QTableWidgetItem(str(query.value(0))))
        stu_visit_interface.ui.res_table.setItem(i, 1, QtWidgets.QTableWidgetItem(query.value(1)))
        stu_visit_interface.ui.res_table.setItem(i, 2, QtWidgets.QTableWidgetItem(decode_date(query.value(2))))
        stu_visit_interface.ui.res_table.setItem(i, 3, QtWidgets.QTableWidgetItem(query.value(3)))

def add_reservation(stu_visit_interface):
    if(stu_visit_interface.ui.visid.text() == '' or not stu_visit_interface.ui.year.text().isdigit() or not stu_visit_interface.ui.month.text().isdigit() or not stu_visit_interface.ui.day.text().isdigit() or stu_visit_interface.ui.reason.toPlainText() == ''):
        error_msgbox = QtWidgets.QDialog()
        error_msgbox.setAttribute(QtCore.Qt.WA_DeleteOnClose, True)
        error_msgbox.ui = Ui_error_box()
        error_msgbox.ui.setupUi(error_msgbox, "必须提供有效信息")
        error_msgbox.exec_()
    else:
        query = QtSql.QSqlQuery()
        query.prepare("call add_reservation(:username, :visid, :date, :reason, @stat)")
        query.bindValue(':date', encode_date(stu_visit_interface.ui.year.text(), stu_visit_interface.ui.month.text(), stu_visit_interface.ui.day.text()))
        query.bindValue(':username', stu_visit_interface.stuid)
        query.bindValue(':visid', stu_visit_interface.ui.visid.text())
        query.bindValue(':reason', stu_visit_interface.ui.reason.toPlainText())
        query.exec()
        query.exec("select @stat")
        query.next()

        if (query.value(0) > 0):
            error_msgbox = QtWidgets.QDialog()
            error_msgbox.setAttribute(QtCore.Qt.WA_DeleteOnClose, True)
            error_msgbox.ui = Ui_error_box()
            error_msgbox.ui.setupUi(error_msgbox, "无法新增预约")
            error_msgbox.exec_()
        else:
            find_reservation(stu_visit_interface)

def update_reservation(stu_visit_interface):
    if(not stu_visit_interface.ui.resid.text().isdigit()):
        error_msgbox = QtWidgets.QDialog()
        error_msgbox.setAttribute(QtCore.Qt.WA_DeleteOnClose, True)
        error_msgbox.ui = Ui_error_box()
        error_msgbox.ui.setupUi(error_msgbox, "预约号无效")
        error_msgbox.exec_()
    else:
        query = QtSql.QSqlQuery()
        if (not stu_visit_interface.ui.year.text().isdigit() or not stu_visit_interface.ui.month.text().isdigit() or not stu_visit_interface.ui.day.text().isdigit()):
            query.prepare("call update_reservation(:resid, :username, :visid, null, :reason, @stat)")
        else:
            query.prepare("call update_reservation(:resid, :username, :visid, :date, :reason, @stat)")
            query.bindValue(':date', encode_date(stu_visit_interface.ui.year.text(), stu_visit_interface.ui.month.text(), stu_visit_interface.ui.day.text()))
        query.bindValue(':resid', int(stu_visit_interface.ui.resid.text()))
        query.bindValue(':username', stu_visit_interface.stuid)
        query.bindValue(':visid', stu_visit_interface.ui.visid.text())
        query.bindValue(':reason', stu_visit_interface.ui.reason.toPlainText())
        query.exec()
        query.exec("select @stat")
        query.next()

        if (query.value(0) > 0):
            error_msgbox = QtWidgets.QDialog()
            error_msgbox.setAttribute(QtCore.Qt.WA_DeleteOnClose, True)
            error_msgbox.ui = Ui_error_box()
            error_msgbox.ui.setupUi(error_msgbox, "预约信息更新失败")
            error_msgbox.exec_()
        else:
            find_reservation(stu_visit_interface)

def delete_reservation(stu_visit_interface):
    if(not stu_visit_interface.ui.resid.text().isdigit()):
        error_msgbox = QtWidgets.QDialog()
        error_msgbox.setAttribute(QtCore.Qt.WA_DeleteOnClose, True)
        error_msgbox.ui = Ui_error_box()
        error_msgbox.ui.setupUi(error_msgbox, "预约号无效")
        error_msgbox.exec_()
    else:
        query = QtSql.QSqlQuery()
        query.prepare("call delete_reservation(:username, :resid, @stat)")
        query.bindValue(':resid', int(stu_visit_interface.ui.resid.text()))
        query.bindValue(':username', stu_visit_interface.stuid)
        query.exec()
        query.exec("select @stat")
        query.next()

        if (query.value(0) > 0):
            error_msgbox = QtWidgets.QDialog()
            error_msgbox.setAttribute(QtCore.Qt.WA_DeleteOnClose, True)
            error_msgbox.ui = Ui_error_box()
            error_msgbox.ui.setupUi(error_msgbox, f"预约删除失败")
            error_msgbox.exec_()
        else:
            find_reservation(stu_visit_interface)
